# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
#spring profile
spring:
    profiles:
        active: dev
    datasource:
#        type: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/random?useUnicode=true&characterEncoding=utf8
        username: root
        password:
    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate:
                cache:
                    use_second_level_cache: true
                    use_query_cache: false
                    region:
                        factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
                generate_statistics: true
    thymeleaf:
        cache: false
    mail:
        host: email.ujn.edu.cn
        username: cngradms@ujn.edu.cn
        password: wlyrjsyb
        port: 25
#Server config
server:
    port: 3000
    address: localhost
#endpoints config
endpoints:
    shutdown:
        enabled: false
logging:
    level: INFO
    path: I:/pc2
    file: random.log

#randomX config
randonX:
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 31
    cache: #Hibernate 2nd level cache, used by CacheConfig
        timeToLiveSeconds: 3600
        ehcache:
            maxBytesLocalHeap: 256M

#logback
logback:
    level: WARN